# Welcome to Exponential Deep Space!
#
# This config file is meant for settings that affect the whole website, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
#   _____  _____  ___  _  _ ___ _  _ _____ ___   _   _    
#  | __\ \/ / _ \/ _ \| \| | __| \| |_   _|_ _| /_\ | |   
#  | _| >  <|  _/ (_) | .` | _|| .` | | |  | | / _ \| |__ 
#  |___/_/\_\_| _\___/|_|\_|___|_|\_| |_| |___/_/ \_\____|
#     |   \| __| __| _ \    / __| _ \/_\ / __| __|        
#     | |) | _|| _||  _/    \__ \  _/ _ \ (__| _|         
#     |___/|___|___|_|      |___/_|/_/ \_\___|___|        
                                                                 
                                                        



## => Site Settings
##############################
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : Exponential Deep Space
description: > # this means to ignore newlines until "Language & timezone"
  exponential space exploration with batteries included

## => Author and Social
##############################
author:
  type      : organization # "person" (default), "organization"
  name      : Exponential Deep Space
  url       :
  avatar    : # path or url of avatar image
  bio       : Space industries rocketing up
  email     :
  facebook  : # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name/
  linkedin  : # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name/
  github    : # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name




## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg



## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji