# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for development,  DELETE IT IF YOU WANT.


## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : # the base hostname & protocol for your site e.g. https://www.someone.com
baseurl : # does not include hostname
title   : TeXt Theme
description: > # this means to ignore newlines until "Language & timezone"
  TeXt Theme for development.


## => Language and Timezone
##############################
lang: # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values


## => Author and Social
##############################
author:
  type      : organization # "person" (default), "organization"
  name      : TeXt
  url       :
  avatar    : /assets/apple-touch-icon.png
  bio: >
    TeXt Theme for development.
  email     : 1
  facebook  : 1
  twitter   : 1
  googleplus: 1
  weibo     : 1
  douban    : 1
  linkedin  : 1
  github    : 1
  npm       : 1
  telegram  : 1


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: kitian616/jekyll-TeXt-theme
repository_tree: master


## => Paths
##############################
paths:
  root    : # title link url, "/" (default)
  home    : /test/ # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: "h1,h2,h3,h4,h5,h6" # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: true # false (default), true
mathjax_autoNumber: true # false (default), true

## Mermaid
mermaid: true # false (default), true

## Chart
chart: true # false (default), true


## => Paginate
##############################
paginate: 4
paginate_path: /test/page:num # don't change this unless for special need


## => Sources
##############################
sources: unpkg # bootcdn (default), unpkg


## => Comments
##############################
comments:
  provider: false # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  disqus:
    shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  gitalk:
    clientID    : # GitHub Application Client ID
    clientSecret: # GitHub Application Client Secret
    repository  : # GitHub repo
    owner       : # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize GitHub issues, IT IS A LIST.
      # - your GitHub Id


## => Pageview
##############################
pageview:
  provider: false # false (default), "leancloud", "custom"

  ## Leancloud
  leancloud:
    app_id    : # LeanCloud App id
    app_key   : # LeanCloud App key
    app_class : # LeanCloud App class


## => Analytics
##############################
analytics:
  provider: false # false (default), "google", "custom"

  ## Google Analytics
  google:
    tracking_id : # Google Analytics id for the site
    anonymize_ip: false # Anonymize IP tracking for Analytics


## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  # - /docs
  - /node_modules
  # - /screenshots
  # - /test
  - /vendor
  - /_posts
  - /index.html

collections_dir: docs
collections:
  docs:
    output: true
  page:
    output: true
  articles:
    output: true
  languages:
    output: true

defaults:
  - scope:
      path: "test"
    values:
      articles:
        excerpt_type: html
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      category: post
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true
  - scope:
      path: ""
      type: articles
    values:
      show_date: false
  - scope:
      path: ""
      type: languages
    values:
      layout: article
  - scope:
      path: "_docs/en"
    values:
      layout: article
      sidebar:
        nav: docs-en
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_date: false
  - scope:
      path: "_docs/zh"
    values:
      layout: article
      sidebar:
        nav: docs-zh
      license: true
      aside:
        toc: true
      lang: zh
      show_edit_on_github: true
      show_date: false


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

data_dir: /docs/_data
